In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv("C:/Users/vidhy/OneDrive/Pictures/Documents/Chocolate Sales (2).csv")
df

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
0,Jehu Rudeforth,UK,Mint Chip Choco,04/01/2022,"$5,320.00",180
1,Van Tuxwell,India,85% Dark Bars,01/08/2022,"$7,896.00",94
2,Gigi Bohling,India,Peanut Butter Cubes,07/07/2022,"$4,501.00",91
3,Jan Morforth,Australia,Peanut Butter Cubes,27/04/2022,"$12,726.00",342
4,Jehu Rudeforth,UK,Peanut Butter Cubes,24/02/2022,"$13,685.00",184
...,...,...,...,...,...,...
3277,Karlen McCaffrey,Australia,Spicy Special Slims,17/05/2024,"$5,303.58",354
3278,Jehu Rudeforth,USA,White Choc,07/06/2024,"$7,339.32",121
3279,Ches Bonnell,Canada,Organic Choco Syrup,26/07/2024,$616.09,238
3280,Dotty Strutley,India,Eclairs,28/07/2024,"$2,504.62",397
3281,Karlen McCaffrey,India,70% Dark Bites,23/05/2024,"$5,915.87",355

In [3]:
df.shape

(3282, 6)

In [4]:
df.columns

Index(['Sales Person', 'Country', 'Product', 'Date', 'Amount',
       'Boxes Shipped'],
      dtype='object')

In [5]:
df.dtypes

Sales Person     object
Country          object
Product          object
Date             object
Amount           object
Boxes Shipped     int64
dtype: object

In [6]:
df.isna().sum()

Sales Person     0
Country          0
Product          0
Date             0
Amount           0
Boxes Shipped    0
dtype: int64

In [7]:
df.drop(['Date','Amount'],axis=1,inplace=True)
df

          Sales Person    Country              Product  Boxes Shipped
0       Jehu Rudeforth         UK      Mint Chip Choco            180
1          Van Tuxwell      India        85% Dark Bars             94
2         Gigi Bohling      India  Peanut Butter Cubes             91
3         Jan Morforth  Australia  Peanut Butter Cubes            342
4       Jehu Rudeforth         UK  Peanut Butter Cubes            184
...                ...        ...                  ...            ...
3277  Karlen McCaffrey  Australia  Spicy Special Slims            354
3278    Jehu Rudeforth        USA           White Choc            121
3279      Ches Bonnell     Canada  Organic Choco Syrup            238
3280    Dotty Strutley      India              Eclairs            397
3281  Karlen McCaffrey      India       70% Dark Bites            355

[3282 rows x 4 columns]

In [8]:
from sklearn.preprocessing import LabelEncoder
lab=LabelEncoder()
df['Sales Person']=lab.fit_transform(df['Sales Person'])
df['Country']=lab.fit_transform(df['Country'])
df['Product']=lab.fit_transform(df['Product'])

In [9]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)
x_train

array([[19,  3, 17],
       [14,  2,  1],
       [ 7,  1,  8],
       ...,
       [ 2,  4, 21],
       [16,  0,  5],
       [ 6,  3, 17]], shape=(2297, 3))

In [11]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [12]:
from sklearn.svm import SVC
model=SVC()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
y_pred

array([ 46, 100,  10,  46,  21,  46, 144,  21,   7,  51,  59, 100,  10,
         7,  54,  25,  46, 144, 144,  12,  95,  46,  11,  46,  12,  11,
        31,  12,  73,  54,   7,  10,  91,  80,  46,  54,  11,  46,  11,
        46,  46,  91,  46,  46,  51,  12, 133,  10,  95,  21,  14, 100,
       100, 100,  46,  73,   7,  51, 100,  10,  12, 100,  11,  21,  31,
       112,  12, 142,  11,  10,  10,  11,  46,  10, 142,  59,  46,  63,
        21,   7, 133,  51,  11, 133,  12, 100, 100,   7,  10,  24, 100,
        10,  18,  46, 100,  18,  95, 100,   7, 133,  31,  21,  14,  21,
        46,  51,  46,   7,  10,  12, 100,  12,  18,  10, 100,  11, 133,
        95,  11,   7, 142,  10,  10,  10,  51,  12,  18,  73,  24,  54,
        46,  18,  21,  46,  18, 100,  51,  46,  84,  46,  91,  46, 100,
        21,  10,  21, 100,  11,  46,  51,  11,  46, 100,  46, 142,  46,
        91, 144,  59, 133, 144,  71, 144, 133, 100,  12,  21,  95, 100,
        10,  46, 100,  18,  10,  91,  46,  12,  54, 100,  18,  46,   7,
        51,  95,  11,  10, 144,  24,  46,  46,   6, 100,  18,  46,  59,
       142,  67,  73, 144, 144,  21,  21,  46, 100, 133,  18,  46,  25,
        18,  63,  46,  18,  46,  11,  11, 144,  10,  71,  10,  51,  10,
       100,  95, 100,  11, 142,  46,  51, 100,  51,  10,  10, 100, 100,
        54,  18, 158,  46,  91, 100,  59,  10,  11,  21, 100,  10,  10,
        11, 100,  10, 133,  58, 133,  18,   7,  11,  11, 100,  51,  21,
        46,  71,  54, 100, 133,  12,  46, 100,  82,  25,  91, 102,  46,
        25,  12, 100,  46,  18, 133,  51,  82, 144, 133,  46,  46,  10,
        18,  73,  84,  84, 144, 158, 158,  46,   7,  46,  18,  95,  73,
       133, 133,  10,  95,  18, 133,  18,  21,  11,  46, 100,  10,   7,
        51, 142,  11,  51,  51, 100, 142,  12,  46,   7,  95,  11, 158,
        46,  51,  10,  10,  95,  25, 100,  91,  84, 142,  51,  31, 100,
        10,  67, 133, 100,  10,  10, 100,  18, 144,  18, 142,  10,  46,
        31,   7,  59,   4, 142, 142,  21, 133,  51,  46,  46,  95,  10,
        58,  18,  11, 100,  12,  82,  18,  84,   7, 100,  84,  67,  12,
        95,  67,  58,  21,   7,  10, 144,   7,  11, 158,  10,  87, 158,
         7,  46,  46, 100,  18,  80, 142,   7,  46,  12,  21, 133, 142,
       100, 100,  10,  21,  46, 100,  54,  51, 100, 144,  46,  14, 100,
        73,  10,  46,  46,  54,   7,  12, 133, 100, 100,  11,  46,  71,
       100,   6, 100,  46,  10,  25,  46,  12,  10,  10,  82, 100,  58,
        21,  46,  10,  12,   7, 133,  10,  46,  21,  58,  12,  25,  10,
        10,   7,  46,  49,   4,  58,  12,  10, 100,  24,  10, 133,  21,
        84, 158, 100,  95, 142,  10,  10,  46, 144,  58,  67,  91,  18,
         7,  11,  58,  18,  54,  10,  10,  10,  21,  54, 100, 133,  51,
        46,  18, 142,  27,  46,  10, 179,  46,  54,  21,  10,  10, 100,
        71,  46,  21, 144, 142, 133,  84,  46,  12, 100, 158,  59,  12,
        46, 142,  10,  11,  63,  46,  18, 144,  46,  46,  10,  58,  15,
       158,  11, 142,  12,  12,  46,  12,  46,  10,  54,  21, 100,  12,
        10,  80,  59,  18,  91,  59,   7,  11,  10, 100,  11,  12,  21,
        18,  12,  10,  95,  51,  10,  46, 100,  46,  24,  46,  46,  46,
        21, 144,  11,  18,  10,   7,  59, 100,  12, 100,  84,  46,  46,
        59,  51,  46,  31,  14,  46,  80,  11, 144,  51,  46,   7,  71,
       158,  10,  11,  10,   7,  11,  59,  10,  46,  46,  21,  82, 100,
        51,  51,  18,  46,  46,  12,  46,  91,  10,  87,  25,  10,  95,
        46,  63, 133, 158,  58,  10,  46,  10,  11,  10,  51,  63,  11,
       133,  10, 100,  46,  10,  46, 142,  10,  10,  21,  10,  18,  11,
       144, 133,   7,  46, 100,  11,  18,  27,  12, 100,  51,  95,  51,
       133,  18,  46,  51, 133, 144,  46,  95,  46, 142,  15,  11, 100,
        67,  12,  12, 100,  18,  10,  46,  59,   7,  51,  71,  46,  46,
        21, 100,  27, 100,  71,  11, 144,  10,  10,  46,  46,  12, 133,
        10,  46, 100,  11, 100,  18,  18,  87,  11,  54,  46, 100,  95,
        46, 133, 107,  12, 175,  11,  46,  54,  18,  10,  21,  51,  10,
       158, 100,  95, 100, 144,  18, 100,  10,  46,   7, 100,  18,  46,
       100,  10,  18,  84,  12,  10,  12,   7,  59,  24, 144,   7, 100,
        46,  12, 100,  11,  58,  21,  46,  46, 144,  14,  54, 100, 100,
        31,   7, 112, 100,  71,  46,  46,  12,   7,  11,  73,  51,   7,
        10,  51,  46,  21,  51, 133,  21,  18, 133,  46,  58,  31,  24,
        46,  80,  11,  46,  46,  51,  10,  46,  11,  12,  67, 100,  46,
       100,  71, 100,  59,   7,  91,  14,  11,  12,  12,  59, 133,  46,
        54,  46,  11,  12,  71,  18, 102, 144,  46,  51,  82,  58, 133,
        46, 144,  46,  10,  25,  46,  18,  67,   7,  10,  91,  46,  67,
       133, 179, 102,  73,  18,  12,  10, 100,  11,   6, 158,  82, 100,
        18,  73,  18,  87, 133,  10, 100,  46,   7, 100,  51,  18,  59,
        10,  91, 100,  10, 100,  95,  95, 133,   7, 100,  95,  46,  46,
       133,  10,  10,  10, 133, 142,  11,  31,  67,  12, 175,  14,  46,
        84,  71, 301,  95,  11,  46,  18, 100, 142,  18,  46,  46,  14,
        46,  46, 133,   7,  91,  46,  10,  95,  25,  51,  91,  67,  11,
        10,  10,  54, 100, 100, 100,  46,  18, 100,  51,  46,  54,  46,
         7,  10, 144,  46,  12,  46, 142,  82,   7, 100,  14, 100, 100,
       100,   7,  10, 100, 142,  51,  91,  71, 179,  10,  95,  14, 133,
        11, 144,  95,  91,  11,  46,  73, 142,  54,  54,  10,  71,  12,
        95, 100,  14,  51,  73,  18, 100,  24,  87, 100])

In [13]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
cm

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(364, 364))

In [14]:
score=accuracy_score(y_test,y_pred)*100
score

1.015228426395939

In [15]:
from sklearn.metrics import classification_report
report=classification_report(y_test,y_pred)
print(report)

              precision    recall  f1-score   support

           1       0.00      0.00      0.00         2
           2       0.00      0.00      0.00         5
           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00         4
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         5
           7       0.02      0.25      0.04         4
           8       0.00      0.00      0.00         5
           9       0.00      0.00      0.00         1
          10       0.00      0.00      0.00         0
          11       0.04      0.33      0.06         6
          12       0.02      0.12      0.03         8
          13       0.00      0.00      0.00         1
          14       0.00      0.00      0.00         1
          15       0.00      0.00      0.00         3
          16       0.00      0.00      0.00         3
          17       0.00      0.00      0.00         2
          18       0.00      0.00      0.00         4
          19       0.00      0.00      0.00         2
          20       0.00      0.00      0.00         1
          21       0.03      0.25      0.05         4
          22       0.00      0.00      0.00         6
          23       0.00      0.00      0.00         7
          24       0.00      0.00      0.00         8
          25       0.00      0.00      0.00         0
          26       0.00      0.00      0.00        10
          27       0.00      0.00      0.00         7
          28       0.00      0.00      0.00         3
          29       0.00      0.00      0.00         3
          30       0.00      0.00      0.00         1
          31       0.00      0.00      0.00         4
          32       0.00      0.00      0.00         4
          33       0.00      0.00      0.00         3
          34       0.00      0.00      0.00         1
          35       0.00      0.00      0.00         1
          38       0.00      0.00      0.00         2
          40       0.00      0.00      0.00         3
          41       0.00      0.00      0.00         5
          42       0.00      0.00      0.00         3
          43       0.00      0.00      0.00         3
          44       0.00      0.00      0.00         7
          45       0.00      0.00      0.00         9
          46       0.02      0.50      0.04         6
          47       0.00      0.00      0.00         1
          48       0.00      0.00      0.00         3
          49       0.00      0.00      0.00         4
          50       0.00      0.00      0.00         1
          51       0.00      0.00      0.00         1
          52       0.00      0.00      0.00         5
          53       0.00      0.00      0.00         1
          54       0.00      0.00      0.00         6
          55       0.00      0.00      0.00         5
          56       0.00      0.00      0.00         4
          57       0.00      0.00      0.00         2
          58       0.00      0.00      0.00         7
          59       0.00      0.00      0.00         2
          60       0.00      0.00      0.00         4
          61       0.00      0.00      0.00         3
          62       0.00      0.00      0.00         4
          63       0.00      0.00      0.00         1
          64       0.00      0.00      0.00         4
          65       0.00      0.00      0.00         6
          66       0.00      0.00      0.00         2
          67       0.00      0.00      0.00         4
          68       0.00      0.00      0.00         3
          69       0.00      0.00      0.00         6
          70       0.00      0.00      0.00         3
          71       0.00      0.00      0.00         2
          72       0.00      0.00      0.00         6
          73       0.00      0.00      0.00         7
          74       0.00      0.00      0.00         2
          75       0.00      0.00      0.00         2
          76       0.00      0.00      0.00         3
          77       0.00      0.00      0.00         2
          78       0.00      0.00      0.00         4
          79       0.00      0.00      0.00         2
          80       0.00      0.00      0.00         5
          81       0.00      0.00      0.00         3
          82       0.00      0.00      0.00         1
          83       0.00      0.00      0.00         7
          84       0.00      0.00      0.00         6
          85       0.00      0.00      0.00        11
          86       0.00      0.00      0.00         7
          87       0.00      0.00      0.00         1
          88       0.00      0.00      0.00         7
          89       0.00      0.00      0.00         3
          90       0.00      0.00      0.00         2
          91       0.00      0.00      0.00         3
          92       0.00      0.00      0.00         3
          93       0.00      0.00      0.00         4
          94       0.00      0.00      0.00         6
          95       0.00      0.00      0.00         2
          96       0.00      0.00      0.00         4
          97       0.00      0.00      0.00         2
          98       0.00      0.00      0.00         1
          99       0.00      0.00      0.00         3
         100       0.00      0.00      0.00         4
         101       0.00      0.00      0.00         6
         102       0.00      0.00      0.00         8
         103       0.00      0.00      0.00         7
         104       0.00      0.00      0.00         4
         105       0.00      0.00      0.00         3
         106       0.00      0.00      0.00         5
         107       0.00      0.00      0.00         5
         108       0.00      0.00      0.00         4
         109       0.00      0.00      0.00         4
         110       0.00      0.00      0.00         5
         111       0.00      0.00      0.00        10
         112       0.00      0.00      0.00         2
         113       0.00      0.00      0.00         2
         114       0.00      0.00      0.00         3
         115       0.00      0.00      0.00         6
         116       0.00      0.00      0.00         2
         117       0.00      0.00      0.00         4
         118       0.00      0.00      0.00         3
         119       0.00      0.00      0.00         3
         120       0.00      0.00      0.00         3
         121       0.00      0.00      0.00         6
         122       0.00      0.00      0.00         2
         123       0.00      0.00      0.00         3
         124       0.00      0.00      0.00         2
         125       0.00      0.00      0.00         5
         126       0.00      0.00      0.00         3
         127       0.00      0.00      0.00         2
         128       0.00      0.00      0.00         5
         129       0.00      0.00      0.00         2
         130       0.00      0.00      0.00         5
         131       0.00      0.00      0.00         5
         132       0.00      0.00      0.00         8
         133       0.02      0.25      0.04         4
         134       0.00      0.00      0.00         3
         135       0.00      0.00      0.00         3
         136       0.00      0.00      0.00         5
         137       0.00      0.00      0.00         5
         138       0.00      0.00      0.00         2
         139       0.00      0.00      0.00         5
         140       0.00      0.00      0.00         6
         141       0.00      0.00      0.00         3
         142       0.04      0.25      0.07         4
         143       0.00      0.00      0.00         4
         144       0.00      0.00      0.00         1
         145       0.00      0.00      0.00         3
         146       0.00      0.00      0.00         2
         147       0.00      0.00      0.00         3
         148       0.00      0.00      0.00         3
         149       0.00      0.00      0.00         6
         150       0.00      0.00      0.00         2
         151       0.00      0.00      0.00         3
         152       0.00      0.00      0.00         5
         153       0.00      0.00      0.00         3
         154       0.00      0.00      0.00         8
         155       0.00      0.00      0.00         6
         156       0.00      0.00      0.00         1
         157       0.00      0.00      0.00         2
         158       0.00      0.00      0.00         4
         159       0.00      0.00      0.00         6
         160       0.00      0.00      0.00         1
         162       0.00      0.00      0.00         2
         163       0.00      0.00      0.00         4
         164       0.00      0.00      0.00         4
         166       0.00      0.00      0.00         3
         167       0.00      0.00      0.00         3
         168       0.00      0.00      0.00         1
         169       0.00      0.00      0.00         2
         170       0.00      0.00      0.00         3
         171       0.00      0.00      0.00         1
         172       0.00      0.00      0.00         5
         173       0.00      0.00      0.00         4
         174       0.00      0.00      0.00         6
         175       0.00      0.00      0.00         4
         177       0.00      0.00      0.00         4
         178       0.00      0.00      0.00         3
         179       0.00      0.00      0.00         6
         180       0.00      0.00      0.00         5
         181       0.00      0.00      0.00         1
         182       0.00      0.00      0.00         5
         183       0.00      0.00      0.00         4
         184       0.00      0.00      0.00         3
         186       0.00      0.00      0.00         2
         187       0.00      0.00      0.00         2
         188       0.00      0.00      0.00         1
         191       0.00      0.00      0.00         2
         192       0.00      0.00      0.00         2
         193       0.00      0.00      0.00         1
         194       0.00      0.00      0.00         2
         196       0.00      0.00      0.00         3
         197       0.00      0.00      0.00         1
         198       0.00      0.00      0.00         2
         200       0.00      0.00      0.00         2
         201       0.00      0.00      0.00         6
         202       0.00      0.00      0.00         2
         203       0.00      0.00      0.00         2
         204       0.00      0.00      0.00         3
         205       0.00      0.00      0.00         1
         206       0.00      0.00      0.00         1
         208       0.00      0.00      0.00         1
         209       0.00      0.00      0.00         3
         211       0.00      0.00      0.00         1
         212       0.00      0.00      0.00         2
         213       0.00      0.00      0.00         3
         214       0.00      0.00      0.00         1
         216       0.00      0.00      0.00         3
         217       0.00      0.00      0.00         3
         219       0.00      0.00      0.00         2
         220       0.00      0.00      0.00         1
         222       0.00      0.00      0.00         4
         223       0.00      0.00      0.00         2
         224       0.00      0.00      0.00         1
         225       0.00      0.00      0.00         2
         226       0.00      0.00      0.00         2
         227       0.00      0.00      0.00         3
         228       0.00      0.00      0.00         1
         229       0.00      0.00      0.00         1
         230       0.00      0.00      0.00         3
         231       0.00      0.00      0.00         6
         232       0.00      0.00      0.00         4
         233       0.00      0.00      0.00         3
         234       0.00      0.00      0.00         3
         235       0.00      0.00      0.00         2
         236       0.00      0.00      0.00         4
         237       0.00      0.00      0.00         1
         238       0.00      0.00      0.00         3
         241       0.00      0.00      0.00         3
         243       0.00      0.00      0.00         1
         244       0.00      0.00      0.00         1
         246       0.00      0.00      0.00         1
         247       0.00      0.00      0.00         5
         248       0.00      0.00      0.00         1
         249       0.00      0.00      0.00         3
         250       0.00      0.00      0.00         1
         252       0.00      0.00      0.00         1
         253       0.00      0.00      0.00         2
         254       0.00      0.00      0.00         2
         256       0.00      0.00      0.00         1
         257       0.00      0.00      0.00         2
         258       0.00      0.00      0.00         2
         259       0.00      0.00      0.00         2
         260       0.00      0.00      0.00         1
         261       0.00      0.00      0.00         1
         262       0.00      0.00      0.00         2
         264       0.00      0.00      0.00         2
         265       0.00      0.00      0.00         1
         268       0.00      0.00      0.00         3
         269       0.00      0.00      0.00         1
         270       0.00      0.00      0.00         3
         271       0.00      0.00      0.00         6
         272       0.00      0.00      0.00         1
         273       0.00      0.00      0.00         1
         274       0.00      0.00      0.00         1
         275       0.00      0.00      0.00         1
         276       0.00      0.00      0.00         2
         277       0.00      0.00      0.00         4
         279       0.00      0.00      0.00         1
         280       0.00      0.00      0.00         1
         281       0.00      0.00      0.00         2
         282       0.00      0.00      0.00         3
         283       0.00      0.00      0.00         1
         284       0.00      0.00      0.00         3
         285       0.00      0.00      0.00         1
         286       0.00      0.00      0.00         2
         287       0.00      0.00      0.00         2
         288       0.00      0.00      0.00         2
         293       0.00      0.00      0.00         3
         295       0.00      0.00      0.00         1
         296       0.00      0.00      0.00         1
         297       0.00      0.00      0.00         1
         298       0.00      0.00      0.00         2
         300       0.00      0.00      0.00         1
         301       0.00      0.00      0.00         1
         303       0.00      0.00      0.00         3
         304       0.00      0.00      0.00         2
         306       0.00      0.00      0.00         3
         307       0.00      0.00      0.00         1
         311       0.00      0.00      0.00         1
         312       0.00      0.00      0.00         2
         313       0.00      0.00      0.00         3
         314       0.00      0.00      0.00         1
         317       0.00      0.00      0.00         3
         320       0.00      0.00      0.00         1
         321       0.00      0.00      0.00         2
         323       0.00      0.00      0.00         2
         325       0.00      0.00      0.00         1
         327       0.00      0.00      0.00         1
         328       0.00      0.00      0.00         1
         329       0.00      0.00      0.00         1
         330       0.00      0.00      0.00         1
         335       0.00      0.00      0.00         1
         337       0.00      0.00      0.00         2
         340       0.00      0.00      0.00         3
         341       0.00      0.00      0.00         1
         344       0.00      0.00      0.00         3
         347       0.00      0.00      0.00         3
         350       0.00      0.00      0.00         1
         351       0.00      0.00      0.00         1
         352       0.00      0.00      0.00         1
         353       0.00      0.00      0.00         1
         354       0.00      0.00      0.00         1
         355       0.00      0.00      0.00         1
         358       0.00      0.00      0.00         2
         360       0.00      0.00      0.00         1
         361       0.00      0.00      0.00         1
         363       0.00      0.00      0.00         1
         365       0.00      0.00      0.00         1
         366       0.00      0.00      0.00         1
         368       0.00      0.00      0.00         1
         373       0.00      0.00      0.00         1
         381       0.00      0.00      0.00         1
         384       0.00      0.00      0.00         1
         385       0.00      0.00      0.00         1
         386       0.00      0.00      0.00         1
         388       0.00      0.00      0.00         1
         389       0.00      0.00      0.00         2
         390       0.00      0.00      0.00         2
         392       0.00      0.00      0.00         3
         395       0.00      0.00      0.00         1
         397       0.00      0.00      0.00         1
         398       0.00      0.00      0.00         1
         400       0.00      0.00      0.00         1
         402       0.00      0.00      0.00         2
         403       0.00      0.00      0.00         1
         404       0.00      0.00      0.00         1
         406       0.00      0.00      0.00         1
         407       0.00      0.00      0.00         1
         408       0.00      0.00      0.00         1
         409       0.00      0.00      0.00         2
         410       0.00      0.00      0.00         1
         411       0.00      0.00      0.00         3
         413       0.00      0.00      0.00         1
         415       0.00      0.00      0.00         2
         417       0.00      0.00      0.00         1
         418       0.00      0.00      0.00         2
         419       0.00      0.00      0.00         1
         420       0.00      0.00      0.00         1
         421       0.00      0.00      0.00         1
         422       0.00      0.00      0.00         1
         430       0.00      0.00      0.00         3
         432       0.00      0.00      0.00         1
         434       0.00      0.00      0.00         1
         435       0.00      0.00      0.00         1
         442       0.00      0.00      0.00         1
         443       0.00      0.00      0.00         1
         446       0.00      0.00      0.00         1
         449       0.00      0.00      0.00         2
         452       0.00      0.00      0.00         1
         454       0.00      0.00      0.00         1
         457       0.00      0.00      0.00         1
         461       0.00      0.00      0.00         1
         468       0.00      0.00      0.00         1
         469       0.00      0.00      0.00         1
         475       0.00      0.00      0.00         1
         485       0.00      0.00      0.00         1
         487       0.00      0.00      0.00         1
         488       0.00      0.00      0.00         1
         490       0.00      0.00      0.00         1
         491       0.00      0.00      0.00         1
         506       0.00      0.00      0.00         1
         507       0.00      0.00      0.00         1
         523       0.00      0.00      0.00         1
         524       0.00      0.00      0.00         2
         538       0.00      0.00      0.00         1
         539       0.00      0.00      0.00         1
         540       0.00      0.00      0.00         1
         583       0.00      0.00      0.00         1
         778       0.00      0.00      0.00         1

    accuracy                           0.01       985
   macro avg       0.00      0.01      0.00       985
weighted avg       0.00      0.01      0.00       985

C:\Users\vidhy\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\vidhy\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\vidhy\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\vidhy\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\vidhy\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\vidhy\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])